"""Generate the paper's numbers from ``results/*.json``.

Writes ``report/generated/`` — a macro file of scalars plus one ``.tex`` file per
table — which ``report/main.tex`` ``\\input``s. Nothing numeric is typed by hand
into the paper, so a re-run of the experiments updates the prose, the tables and
the figures together, and a stale number is not expressible.

Usage::

    python scripts/make_report_tables.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
RESULTS_DIR = REPO_ROOT / "results"
OUT_DIR = REPO_ROOT / "report" / "generated"


def load(name: str) -> dict[str, Any] | None:
    path = RESULTS_DIR / f"{name}.json"
    if not path.exists():
        print(f"  [warn] missing {path.name}")
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def tex_escape(text: str) -> str:
    """Escape the characters that actually appear in our labels."""
    for old, new in (("&", r"\&"), ("%", r"\%"), ("_", r"\_"), ("#", r"\#")):
        text = text.replace(old, new)
    return text


def num(value: Any, digits: int = 4) -> str:
    if value is None or (isinstance(value, float) and value != value):
        return "--"
    return f"{float(value):.{digits}f}"


# ----------------------------------------------------------------- macros


def write_macros() -> None:
    """Scalars quoted inline in the prose."""
    lines = [
        "% Generated by scripts/make_report_tables.py -- do not edit by hand.",
        "",
    ]

    def define(name: str, value: Any) -> None:
        lines.append(rf"\newcommand{{\{name}}}{{{value}}}")

    comparison = load("model_comparison_ml-100k")
    if comparison:
        rows = comparison["table"]
        best = min(rows, key=lambda r: r["test_rmse"])
        by_label = {r["label"]: r for r in rows}
        define("BestModelLabel", tex_escape(best["label"]))
        define("BestRMSE", num(best["test_rmse"]))
        define("BestRMSECI", num(best["test_rmse_ci95"]))
        define("NumSeeds", len(comparison["seeds"]))
        for key, label in (
            ("GlobalMeanRMSE", "Global mean"),
            ("ItemMeanRMSE", "Item mean"),
            ("UserMeanRMSE", "User mean"),
            ("BiasBaselineRMSE", "Bias baseline"),
            ("PMFRMSE", "PMF"),
            ("PMFBiasRMSE", "PMF + biases"),
            ("PMFLogisticRMSE", "PMF + logistic link"),
            ("BPMFRMSE", "BPMF"),
        ):
            if label in by_label:
                define(key, num(by_label[label]["test_rmse"]))
                define(key + "CI", num(by_label[label]["test_rmse_ci95"]))

    comparison_1m = load("model_comparison_ml-1m")
    if comparison_1m:
        best = min(comparison_1m["table"], key=lambda r: r["test_rmse"])
        define("BestRMSEOneM", num(best["test_rmse"]))
        define("BestModelLabelOneM", tex_escape(best["label"]))

    legacy = load("legacy_reproduction")
    if legacy:
        define("LegacyRMSE", num(legacy["test_rmse_mean"]))
        define("LegacyRMSEStd", num(legacy["test_rmse_std"]))
        define("LegacyRMSEMin", num(legacy["test_rmse_min"]))
        define("LegacyRMSEMax", num(legacy["test_rmse_max"]))
        define("LegacyReportedTrain", num(legacy["reported_train_rmse_mean"]))
        define("LegacyTrueTrain", num(legacy["true_train_rmse_mean"]))
        define("LegacyPenaltyInflation", num(legacy["penalty_inflation_mean"]))
        define("LegacySeeds", legacy["config"]["n_seeds"])

    scalability = load("scalability")
    if scalability:
        fit = scalability["loglog_fit"]
        define("ScalingSlope", num(fit["slope"], 3))
        define("ScalingSlopeLow", num(fit["slope_ci_low"], 3))
        define("ScalingSlopeHigh", num(fit["slope_ci_high"], 3))
        define("ScalingRSquared", num(fit["r_squared"], 3))
        define("ScalingSupported", "yes" if scalability.get("within_dataset_at_most_linear") else "no")
        define("ScalingMaxN", f"{max(r['n_train_ratings'] for r in scalability['table']):,}")
        define("ScalingMinN", f"{min(r['n_train_ratings'] for r in scalability['table']):,}")

        # Per-dataset exponents, quoted separately because the pooled fit mixes
        # growth in N with growth in the number of entities.
        for key, suffix in (("ml-100k", "OneHundredK"), ("ml-1m", "OneM")):
            per = scalability.get("per_dataset_fit", {}).get(key)
            if per:
                define(
                    f"ScalingSlope{suffix}",
                    f"{num(per['slope'], 3)}~[{num(per['slope_ci_low'], 3)}, "
                    f"{num(per['slope_ci_high'], 3)}]",
                )

    claims = load("claim_verification_ml-100k")
    if claims:
        define("NumClaims", len(claims["claims"]))
        first = next((c for c in claims["claims"] if c["claim_id"] == "C1"), None)
        if first:
            define("ClaimedRMSE", num(first["claimed_value"]))
            define("ClaimVerdict", first["verdict"].lower())
            define("ClaimConfigsTried", first.get("n_configurations_tried", "--"))
            define("ClaimConfigsBetter", first.get("n_configurations_better_than_claim", "--"))
            define("ClaimBestReachable", num(first.get("best_achievable_test_rmse")))
        bounded = next((c for c in claims["claims"] if c["claim_id"] == "C3"), None)
        if bounded:
            define("LogisticGain", num(bounded.get("logistic_gain_over_clipped_identity")))
            define("ClipGain", num(bounded.get("clipping_gain")))
            define(
                "IdentityOutOfRangePct",
                num(100 * (bounded.get("identity_out_of_range_fraction") or 0), 2),
            )

    dims = load("latent_dimension_ml-100k")
    if dims:
        define("BestLatentDim", dims["best_n_factors"])
        define("BestLatentRMSE", num(dims["best_test_rmse"]))

    reg = load("regularisation_ml-100k")
    if reg:
        define("BestLambda", reg["best_reg"])
        define("BestLambdaRMSE", num(reg["best_test_rmse"]))
        define("NoRegCost", num(reg.get("cost_of_no_regularisation")))

    stats = load("dataset_statistics")
    if stats:
        for row in stats["table"]:
            suffix = "OneHundredK" if row["dataset"] == "ml-100k" else "OneM"
            define(f"NUsers{suffix}", f"{row['n_users']:,}")
            define(f"NItems{suffix}", f"{row['n_items']:,}")
            define(f"NRatings{suffix}", f"{row['n_ratings']:,}")
            define(f"Density{suffix}", num(row["density_pct"], 2))

    lines.append("")
    (OUT_DIR / "macros.tex").write_text("\n".join(lines), encoding="utf-8")
    print(f"  [tex] macros.tex ({len(lines) - 3} macros)")


# ----------------------------------------------------------------- tables


def _protect_leading_bracket(cell: str) -> str:
    r"""Brace a cell that starts with ``[``.

    In a tabular, a row following ``\\`` that begins with ``[`` is parsed as
    ``\\[<length>]`` — the row separator's optional vertical-space argument —
    which swallows the bracket and everything up to the next ``]``. The
    cold-start bins ("[0, 10)") hit this exactly. Bracing the cell stops the
    parser looking for an optional argument.
    """
    return f"{{{cell}}}" if cell.lstrip().startswith("[") else cell


def table(name: str, spec: str, header: list[str], rows: list[list[str]], note: str = "") -> None:
    body = [
        "% Generated by scripts/make_report_tables.py -- do not edit by hand.",
        rf"\begin{{tabular}}{{{spec}}}",
        r"\toprule",
        " & ".join(header) + r" \\",
        r"\midrule",
    ]
    body += [
        " & ".join(_protect_leading_bracket(cell) for cell in row) + r" \\" for row in rows
    ]
    body += [r"\bottomrule", r"\end{tabular}"]
    if note:
        body.append(rf"% note: {note}")
    (OUT_DIR / f"{name}.tex").write_text("\n".join(body) + "\n", encoding="utf-8")
    print(f"  [tex] {name}.tex ({len(rows)} rows)")


def table_datasets() -> None:
    payload = load("dataset_statistics")
    if not payload:
        return
    rows = []
    for row in payload["table"]:
        rows.append([
            tex_escape(row["dataset"]),
            f"{row['n_users']:,}",
            f"{row['n_items']:,}",
            f"{row['n_ratings']:,}",
            num(row["density_pct"], 2) + r"\%",
            num(row["rating_mean"], 2),
            f"{row['ratings_per_user_median']:.0f}",
            f"{row['ratings_per_item_median']:.0f}",
        ])
    table(
        "table_datasets",
        "lrrrrrrr",
        ["Dataset", "Users", "Items", "Ratings", "Density", "Mean", r"Med.\ $n_u$", r"Med.\ $n_i$"],
        rows,
    )


def table_comparison(dataset: str, name: str) -> None:
    payload = load(f"model_comparison_{dataset}")
    if not payload:
        return
    rows = []
    for row in sorted(payload["table"], key=lambda r: r["test_rmse"]):
        label = tex_escape(row["label"])
        is_baseline = any(t in row["label"] for t in ("mean", "Bias baseline"))
        if not is_baseline:
            label = rf"\textbf{{{label}}}"
        rows.append([
            label,
            num(row["test_rmse"]) + rf"$\,\pm\,${num(row['test_rmse_ci95'])}",
            num(row["test_mae"]),
            num(row["train_rmse"]),
            f"{row['fit_seconds']:.1f}",
        ])
    table(
        name,
        "lcccr",
        ["Model", "Test RMSE", "Test MAE", "Train RMSE", "Fit (s)"],
        rows,
    )


def table_claims() -> None:
    payload = load("claim_verification_ml-100k")
    if not payload:
        return
    rows = [
        [c["claim_id"], tex_escape(_shorten(c["claim"])), rf"\textsc{{{c['verdict'].lower()}}}"]
        for c in payload["claims"]
    ]
    table("table_claims", "lll", ["", "Claim from the original report", "Verdict"], rows)


def _shorten(text: str, limit: int = 62) -> str:
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "\\ldots"


def table_latent_dimension() -> None:
    payload = load("latent_dimension_ml-100k")
    if not payload:
        return
    rows = [
        [
            str(row["n_factors"]),
            num(row["train_rmse"]),
            num(row["test_rmse"]) + rf"$\,\pm\,${num(row['test_rmse_ci95'])}",
            num(row["test_rmse_no_early_stop"]),
            f"{row['epochs_run']:.0f}",
        ]
        for row in payload["table"]
    ]
    table(
        "table_latent_dimension",
        "rcccr",
        ["$d$", "Train", "Test", "Test (no ES)", "Epochs"],
        rows,
    )


def table_regularisation() -> None:
    payload = load("regularisation_ml-100k")
    if not payload:
        return
    rows = [
        [
            f"{row['reg']:g}",
            num(row["train_rmse"]),
            num(row["test_rmse"]),
            num(row["generalisation_gap"]),
        ]
        for row in payload["table"]
    ]
    table("table_regularisation", "rccc", [r"$\lambda$", "Train", "Test", "Gap"], rows)


def table_cold_start() -> None:
    payload = load("cold_start_ml-100k")
    if not payload:
        return
    first = payload["table"][0]
    models = [k for k in first if k not in ("bin", "n_test_ratings") and not k.endswith("ci95")]
    rows = []
    for row in payload["table"]:
        rows.append(
            [tex_escape(row["bin"]), f"{row['n_test_ratings']:,}"]
            + [num(row[m]) if row[m] is not None else "--" for m in models]
        )
    table(
        "table_cold_start",
        "lr" + "c" * len(models),
        ["Ratings by user", "$n$"] + [tex_escape(m) for m in models],
        rows,
    )


def table_ranking() -> None:
    payload = load("ranking_comparison_ml-100k")
    if not payload:
        return
    k = payload["k"]
    rows = [
        [
            tex_escape(row["label"]),
            num(row[f"precision@{k}"], 4),
            num(row[f"recall@{k}"], 4),
            num(row[f"ndcg@{k}"], 4),
        ]
        for row in payload["table"]
    ]
    table(
        "table_ranking",
        "lccc",
        ["Model", f"P@{k}", f"R@{k}", f"NDCG@{k}"],
        rows,
    )


def table_scalability() -> None:
    payload = load("scalability")
    if not payload:
        return
    rows = [
        [
            tex_escape(row["dataset"]),
            f"{row['n_train_ratings']:,}",
            f"{1000 * row['seconds_per_epoch']:.1f}",
            f"{row['microseconds_per_rating']:.3f}",
        ]
        for row in payload["table"]
    ]
    table(
        "table_scalability",
        "lrrr",
        ["Dataset", "$N$", "ms / epoch", r"$\mu$s / rating"],
        rows,
    )

    # The per-rating column is the one that shows the effect directly: it is
    # flat within a dataset and steps up between them.
    fits = payload.get("per_dataset_fit", {})
    if fits:
        fit_rows = [
            [
                tex_escape(dataset),
                f"{fit['slope']:.3f}",
                f"[{fit['slope_ci_low']:.3f}, {fit['slope_ci_high']:.3f}]",
                f"{fit['r_squared']:.4f}",
                "yes" if fit["slope_ci_low"] <= 1.0 else "no",
            ]
            for dataset, fit in fits.items()
        ]
        pooled = payload["loglog_fit"]
        fit_rows.append([
            r"\emph{pooled}",
            f"{pooled['slope']:.3f}",
            f"[{pooled['slope_ci_low']:.3f}, {pooled['slope_ci_high']:.3f}]",
            f"{pooled['r_squared']:.4f}",
            "yes" if pooled["slope_ci_low"] <= 1.0 else "no",
        ])
        table(
            "table_scaling_fits",
            "lcccc",
            ["Fit", "Exponent $b$", "95\\% CI", "$R^2$", "At most linear"],
            fit_rows,
        )


def table_link_function() -> None:
    payload = load("link_function_ml-100k")
    if not payload:
        return
    rows = [
        [
            tex_escape(row["variant"]),
            num(row["test_rmse"]),
            num(row["test_mae"]),
            num(100 * row["out_of_range_fraction"], 2) + r"\%",
            f"[{row['min_prediction']:.2f}, {row['max_prediction']:.2f}]",
        ]
        for row in payload["table"]
    ]
    table(
        "table_link_function",
        "lcccc",
        ["Variant", "Test RMSE", "Test MAE", "Out of range", "Prediction range"],
        rows,
    )


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    print("=== generating report numbers ===")
    write_macros()
    table_datasets()
    table_comparison("ml-100k", "table_comparison_100k")
    table_comparison("ml-1m", "table_comparison_1m")
    table_claims()
    table_latent_dimension()
    table_regularisation()
    table_cold_start()
    table_ranking()
    table_scalability()
    table_link_function()
    print(f"  -> {OUT_DIR.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
